site:
  title: "Les Fourmis Du Web"
  tagline: "An IT tech blog (and more)"
  author: "Simon Fonteneau"

languages:
  - code: "fr"
    label: "Français"
    path: "/"
  - code: "en"
    label: "English"
    path: "/en/"

menu:
  - label: "Blog"
    href: "/"
  - label: "Wiki"
    href: "https://wiki.lesfourmisduweb.org/"
  - label: "Git"
    href: "https://github.com/sfonteneau"
  - label: "Contact"
    href: "mailto:blog@lesfourmisduweb.org"

# Pagination de la page d'accueil (liste des articles)
pagination:
  # Nombre maximum d'articles affichés par page (par langue)
  posts_per_page: 10
